using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

// Example of how to create and apply migrations
public class MigrationExample
{
    public static void CreateMigration()
    {
        // In Package Manager Console:
        // Add-Migration InitialCreate
        // Add-Migration AddCourseDescription
        
        // Or in .NET CLI:
        // dotnet ef migrations add InitialCreate
        // dotnet ef migrations add AddCourseDescription
    }
    
    public static void ApplyMigration()
    {
        // In Package Manager Console:
        // Update-Database
        
        // Or in .NET CLI:
        // dotnet ef database update
    }
}

// Example migration class (auto-generated by EF Core)
[Migration("20231201000000_InitialCreate")]
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Students",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                FirstName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                LastName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                Email = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                EnrollmentDate = table.Column<DateTime>(type: "datetime2", nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Students", x => x.Id);
            });
        
        migrationBuilder.CreateTable(
            name: "Courses",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                Title = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                Credits = table.Column<int>(type: "int", nullable: false, defaultValue: 3)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Courses", x => x.Id);
            });
        
        migrationBuilder.CreateTable(
            name: "Enrollments",
            columns: table => new
            {
                Id = table.Column<int>(type: "int", nullable: false)
                    .Annotation("SqlServer:Identity", "1, 1"),
                StudentId = table.Column<int>(type: "int", nullable: false),
                CourseId = table.Column<int>(type: "int", nullable: false),
                EnrollmentDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                Grade = table.Column<int>(type: "int", nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Enrollments", x => x.Id);
                table.ForeignKey(
                    name: "FK_Enrollments_Courses_CourseId",
                    column: x => x.CourseId,
                    principalTable: "Courses",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
                table.ForeignKey(
                    name: "FK_Enrollments_Students_StudentId",
                    column: x => x.StudentId,
                    principalTable: "Students",
                    principalColumn: "Id",
                    onDelete: ReferentialAction.Cascade);
            });
        
        migrationBuilder.CreateIndex(
            name: "IX_Enrollments_CourseId",
            table: "Enrollments",
            column: "CourseId");
        
        migrationBuilder.CreateIndex(
            name: "IX_Enrollments_StudentId",
            table: "Enrollments",
            column: "StudentId");
        
        migrationBuilder.CreateIndex(
            name: "IX_Students_Email",
            table: "Students",
            column: "Email",
            unique: true);
    }
    
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Enrollments");
        
        migrationBuilder.DropTable(
            name: "Courses");
        
        migrationBuilder.DropTable(
            name: "Students");
    }
}

// Program.cs configuration
public class ProgramConfiguration
{
    public static void ConfigureService(IServiceCollection services, IConfiguration configuration)
    {
        services.AddDbContext<ApplicationDbContext>(options =>
            options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));
        
        // For development with SQLite
        // services.AddDbContext<ApplicationDbContext>(options =>
        //     options.UseSqlite(configuration.GetConnectionString("SqliteConnection")));
        
        // For in-memory database (testing)
        // services.AddDbContext<ApplicationDbContext>(options =>
        //     options.UseInMemoryDatabase("TestDb"));
    }
}

// appsettings.json example
/*
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=StudentDB;Trusted_Connection=true;MultipleActiveResultSets=true",
    "SqliteConnection": "Data Source=student.db"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
*/
